-- Batch 11: deployments table (repo-only, not applied to any live database).
-- Tracks the active release SHA and component versions so all agents report
-- the same active release.
-- This migration is repo-only and never applied against a live DB.

-- ------------------------------------------------------------------
-- 1. Deployments table
-- ------------------------------------------------------------------
create table if not exists public.deployments (
  id                bigint generated by default as identity primary key,
  deployed_sha      text not null,
  tag               text,
  component_versions jsonb not null default '{}',
  deployed_at       timestamptz not null default now(),
  phase             text not null default 'dry-run',
  success           boolean not null default false,
  rollback_performed boolean not null default false,
  constraint deployments_sha_unique unique (deployed_sha)
);

-- ------------------------------------------------------------------
-- 2. Index for fast lookup of the latest deployment
-- ------------------------------------------------------------------
create index if not exists idx_deployments_deployed_at
  on public.deployments (deployed_at desc);

-- ------------------------------------------------------------------
-- 3. View: current active release (most recent successful deployment)
-- ------------------------------------------------------------------
create or replace view public.current_release as
select
  deployed_sha,
  tag,
  component_versions,
  deployed_at
from public.deployments
where success = true
order by deployed_at desc
limit 1;

-- ------------------------------------------------------------------
-- 4. Safe-forward / rollback state documentation
-- ------------------------------------------------------------------
-- Forward: insert into deployments with success=true after all gates pass.
-- Rollback: mark the previous deployment as the active release by
--           inserting a new row with the previous SHA and success=true.
--           The deployments table is append-only; no rows are deleted.
